<?php
include_once($GLOBALS['site']['incroot']."/Html.class.php");
$h = html::singleton();

class Template {
	public $template;
	private $templateText = "default";
	private $home;
	public $menu;
	private $includes = array();
	
	
	public function __construct($menu, $templateText="default") {
		global $incroot;
		$this->templateText = $templateText;
		// echo 'um'.$templateText;
		if ($this->templateText == "none") return;
		include_once($GLOBALS['site']['incroot']."/site/templates/".$this->templateText.".class.php");
		$this->template = new TemplateInstance($this) or die("???");
		$this->menu = $menu;
	}
	
	public function head() {
	  if ($this->templateText == "none") return;
	  global $h, $pageTitle, $site;
	  ////Add scripts/sheets from template
//	  $scripts = explode(",", $this->template->scripts);
//	  $sheets = explode(",", $this->template->stylesheets);
//	  $h->pa($this->includes);
	  $this->includes = array_merge($this->includes, $this->template->scripts, $this->template->stylesheets);
	  ////Add scripts/styles from jsModules
	  include_once($GLOBALS['site']['incroot']."/JsModule.class.php");
	  $jsMods = new JsModule();
	  foreach ($GLOBALS['site']['jsModules'] as $module => $bool) {
		  if ($bool) {
			  	$mod = $jsMods->modules[$module];
		  		$this->includes = array_merge($this->includes, $mod['scripts'], $mod['styles']);
		  }
	  }
 	  ////Add scripts/sheets from $GLOBALS
	  $this->includes = array_merge($this->includes, $GLOBALS['site']['scripts'], $GLOBALS['site']['stylesheets']);
	  ////HTML/head
	  $title = $GLOBALS['site']['siteName'];
	  if ($GLOBALS['site']['pageTitle'] != "") {
		$title .= ': '. $GLOBALS['site']['pageTitle'];
	  }

	  $h->ohtml($title, $this->includes);
	  if (array_key_exists('headerExtra', $GLOBALS['site'])) {
		$h->tnl($GLOBALS['site']['headerExtra']);  
	  }
	  $h->body($this->template->bodyAtts);
//	  $this->skipNav();		
	}

	public function openLayout() {
		global $h;
		////Site structure
		$h->odiv('id="layout"');
		$class = "column123";
		if ($GLOBALS['site']['leftSideBar']['type'] != "none" && $GLOBALS['site']['rightSideBar'] != "none") {
			$class = 'column2';	////left-content-right
			$this->leftSideBar($GLOBALS['site']['leftSideBar']['type'], $GLOBALS['site']['leftSideBar']['args']);
		} else if ($GLOBALS['site']['leftSideBar']['type'] != "none") {
			$class = 'column23';	////left-content
			$this->leftSideBar($GLOBALS['site']['leftSideBar']['type'], $GLOBALS['site']['leftSideBar']['args']);
		} else if ($GLOBALS['site']['rightSideBar'] != "none") {
			$class = 'column12';	////content-right
		}
		$h->odiv('id="content-wrapper" class="'.$class.'"');
		$h->odiv('id="content"');
	}

	function closeLayout() {
		global $h;		
		$h->cdiv('close #content');	////close content
		$h->cdiv('close #content-wrapper');	//close content-wrapper
		//$h->tbr('rsb: ' . $GLOBALS['site']['rightSideBar']);
		if ($GLOBALS['site']['rightSideBar'] != "none") {
			$this->rightSideBar();
		}
		$h->cdiv('close #layout');	//close layout


	}
	
	
	////For accessibility
	public function skipNav() {
	  global $h;
	  ////link array. ids generated by lowercasing and replacing spaces with hyphens
	  $links = array(
	  	array("display" => "Content"),
		array("display" => "Search"),
		array("display" => "Primary Navigation")
	  );
	  if ($GLOBALS['site']['leftSideBar']['type'] != "none") {
		$links[] = 	array("display" => "Secondary Navigation");
	  }
	  ////generate href ids
	  for ($i = 0; $i < count($links); $i++) {
		$links[$i]['href'] = '#'.strtolower(str_replace(" ", "-", $links[$i]['display']));
	  }
	  ////Render
	  $h->odiv('id="skip" class="hide"');
	  $h->p("Skip to:");
	  $h->linkList($links);
	  $h->cdiv();		

	}
	////Website header
	public function heading() {
		if ($this->templateText == "none") return;		
		$this->template->heading();	
	}
	
	////Left side bar
	public function leftSideBar($type, $args) {
		global $h;
		$h->odiv('id="column1"');
		//$h->pa($leftSideBar);
		switch ($type) {
			case "content":
				$h->tnl($args['content']);
				break;
			case 'menu':
				$path = $GLOBALS['site']['settings']['path'];				
//				if ($_SERVER['REMOTE_ADDR'] == '24.1.115.39') echo 'path?!?' . $path.'<br />';				
				if (array_key_exists('path', $args)) {
					$path = $args['path'];
				}
				$path = preg_replace('/\/[a-z0-9A-Z\-_]+\.php$/', '/', $path);
				if (!preg_match("/\/$/", $path)) $path .= "/";
				$xml = $this->menu->getNodeFromPath(array('path'=>$path));
				$array = $this->menu->xmlMenu2array(array('xml'=>$xml, 'root'=>$path));
		//		$h->pa($array);
				$h->linkList($array, 'class="tree" id="lsb-menu"');
				break;
			default:
				$h->tnl("Unsupported sidebar type");
		}
		$h->cdiv(); //close column 1
				
	}

	public function rightSideBar() {
		global $h;
		$h->odiv('id="column3"');
		$h->tnl($GLOBALS['site']['rightSideBar']);
		$h->cdiv('close column3'); //close column 3
	}
	
	public function breadcrumbs($opts=array()) {
	  global $h;
//	  $h->pa($opts);
	  //$h->script('KW_breadcrumbs("UIRR Home","&raquo;",0,1,"index.php",4,5)');		
	  $this->menu->renderBreadcrumbs($opts);
	}
	
	public function footer() {
		if ($this->templateText == "none") return;		
		$this->template->footer();	
	}
	
}
?>
