<?php
$fields = array(
	'header'=>array(
		'fieldtype'=>'intext',
		'label'=>'Header'
	),
	'body'=>array(
		'fieldtype'=>'textarea',
		'label'=>'Body'
	),
	'expire'=>array(
		'fieldtype'=>'date',
		'label'=>'Expire'
	),
	'display'=>array(
		'fieldtype'=>'checkbox',
		'label'=>'Display'
	),	
	'delete'=>array(
		'fieldtype'=>'checkbox',
		'label'=>'Delete'
	),	
);
?>